(()=>{const entries=[{date:'26.09',time:'10:30',type:'Завтрак',dish:'творожный сырок 100 г + орехи + мюсли + 2 бутерброда с авокадо и красной рыбой + омлет с фасолью, перцем и беконом + хлеб + чай',kcal:1265,protein:57,fat:68,carbs:111,accuracy:'примерно'},{date:'26.09',time:'14:32',type:'Обед',dish:'вареники с картошкой 220 г + салат авокадо/помидоры/сыр 89 г',kcal:570,protein:16,fat:21,carbs:80,accuracy:'примерно'},{date:'26.09',time:'17:13',type:'Перекус',dish:'2 круассана парижских с шоколадной начинкой + 1 мармеладка + чай',kcal:405,protein:5,fat:19,carbs:54,accuracy:'смешанная'},{date:'26.09',time:'20:37',type:'Перекус после тренировки',dish:'протеин IPSUM 23 г + вода 300 мл',kcal:113,protein:21,fat:2.3,carbs:0,accuracy:'по упаковке'},{date:'26.09',time:'21:17',type:'Ужин',dish:'пицца «Двойной цыпленок» 25 см + куриные крылья BBQ 3 шт + чай с сахаром',kcal:1228,protein:64,fat:50,carbs:131,accuracy:'примерно'}];
const target={kcal:2900,protein:150,fat:80,carbs:395};
const targetLabel='Цель на сегодня';
const metrics=[...document.querySelectorAll('[data-food-metric]')],ranges=[...document.querySelectorAll('[data-food-range]')],chart=document.getElementById('food-chart'),mealList=document.getElementById('meal-list');
const ids={kcal:'food-kcal',protein:'food-protein',carbs:'food-carbs',fat:'food-fat'};
const subs={kcal:'food-kcal-sub',protein:'food-protein-sub',carbs:'food-carbs-sub',fat:'food-fat-sub'};
const bars={kcal:'food-kcal-bar',protein:'food-protein-bar',carbs:'food-carbs-bar',fat:'food-fat-bar'};
const units={kcal:'ккал',protein:'г',carbs:'г',fat:'г'};
function totals(){return entries.reduce((a,e)=>(a.kcal+=e.kcal,a.protein+=e.protein,a.fat+=e.fat,a.carbs+=e.carbs,a),{kcal:0,protein:0,fat:0,carbs:0})}
function diffText(k,v){const d=target[k]-v;return d>=0?'осталось '+Math.round(d)+' '+units[k]:'перебор '+Math.abs(Math.round(d))+' '+units[k]}
function renderTotals(){const t=totals();Object.keys(ids).forEach(k=>{const el=document.getElementById(ids[k]),sub=document.getElementById(subs[k]),bar=document.getElementById(bars[k]);if(el)el.innerHTML='<span class="food-value-current">'+t[k]+'</span><span class="food-value-target"> / '+target[k]+' '+units[k]+'</span>';if(sub)sub.textContent=targetLabel+' · '+diffText(k,t[k]);if(bar)bar.style.width=Math.min(100,Math.round(t[k]/target[k]*100))+'%'});if(mealList){mealList.classList.remove('chart-empty');mealList.innerHTML=entries.map(e=>'<div style="padding:10px 0;border-bottom:1px solid #e3ebf2"><b>'+e.time+' · '+e.type+'</b><div style="margin-top:4px">'+e.dish+'</div><div class="mut" style="margin-top:4px">'+e.kcal+' ккал · Б '+e.protein+' г · Ж '+e.fat+' г · У '+e.carbs+' г · '+e.accuracy+'</div></div>').join('')}
const p=document.getElementById('protein-distribution');if(p){p.classList.remove('chart-empty');const items=[['Завтрак',57],['Обед',16],['Перекус',5],['После тренировки',21],['Ужин',64]],mx=Math.max(...items.map(x=>x[1]));p.innerHTML='<div class="protein-bars">'+items.map(([name,val])=>'<div class="protein-bar-row"><div class="protein-bar-label">'+name+'</div><div class="protein-bar-track"><div class="protein-bar-fill" style="width:'+Math.round(val/mx*100)+'%"></div></div><div class="protein-bar-value"><b>'+val+' г</b><span>'+Math.round(val/target.protein*100)+'% цели</span></div></div>').join('')+'</div><div class="protein-bar-note"><b>Распределение неравномерное:</b> основной белок приходится на завтрак и ужин; дневные приёмы заметно слабее.</div>'}
const rec=document.querySelector('.nutrition-bottom .card:last-child .analysis');if(rec){rec.innerHTML='<span class="label">Сегодня:</span> учтены все внесённые приёмы пищи — <b>3581 ккал</b>, <b>Б 163 г</b>, <b>Ж 160,3 г</b>, <b>У 376 г</b>. Относительно цели <b>2900 / Б150 / Ж80 / У395</b>: калории выше примерно на <b>681 ккал</b>, белок выше на <b>13 г</b>, жиры выше примерно на <b>80 г</b>, углеводов меньше примерно на <b>19 г</b>. Силовая тренировка 26.09 подтверждена; дополнительное повышение цели до 3100 ккал не применяется, потому что второй тренировки сегодня не зафиксировано.'} }
function renderChart(metric){const t=totals();if(!chart)return;chart.classList.add('chart-empty');const label={kcal:'Калории',protein:'Белок',weight:'Вес',fat:'Жиры',carbs:'Углеводы'}[metric];if(metric==='weight'){chart.textContent='Вес ведётся в отдельном недельном графике.';return}chart.textContent=label+' за 26.09: '+t[metric]+' из '+target[metric]+' '+units[metric]+' ('+Math.round(t[metric]/target[metric]*100)+'%). Для динамики по дням нужны данные за несколько дней.'}
metrics.forEach(b=>b.addEventListener('click',()=>{metrics.forEach(x=>x.classList.remove('active'));b.classList.add('active');renderChart(b.dataset.foodMetric)}));ranges.forEach(b=>b.addEventListener('click',()=>{ranges.forEach(x=>x.classList.remove('active'));b.classList.add('active')}));renderTotals();renderChart('kcal')})();